CREATE TABLE IF NOT EXISTS entusiasmo_agente_mensajes (
  id bigint generated by default as identity primary key,
  participante_email text NOT NULL,
  fecha date NOT NULL,
  tipo_caso text,
  texto_generado text,
  estado text NOT NULL,
  motivo_omision text,
  valoracion text,
  nota text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS entusiasmo_agente_mensajes_participante_fecha_idx
  ON entusiasmo_agente_mensajes (participante_email, fecha DESC);
